---
title: "__*ggtree*__: phylogenetic tree viewer and annotator"
author: "Guangchuang Yu <br> <guangchuangyu@gmail.com> <br> School of Public Health <br> The University of Hong Kong"
date: "`r Sys.Date()`"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{ggtree: phylogenetic tree viewer and annotator}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r style, echo=FALSE, results="asis"}
BiocStyle::markdown()
```


## Tree annotation

```{r fig.width=6, fig.height=5}
nwk <- system.file("extdata", "sample.nwk", package="ggtree")
print(readLines(nwk))
library(ape)
tree <- read.tree(nwk)
library(ggplot2)
library(ggtree)
p <- ggtree(tree)
```

Suppose we have the following data that associated with the tree and would like to attach the annotated value in the tree.

```{r}
dd <- data.frame(taxa=sample(LETTERS[1:13], 6), value=round(abs(rnorm(6))*100))
```
```{r eval=FALSE}
print(dd)
```

```{r echo=FALSE, results='asis'}
knitr::kable(dd)
```

The layer `geom_place` is designed to this task, we input a `data.frame` and specify the column that match the tip and node (if availabe) labels by `map` and a column to attach in the tree by `place`.

```{r fig.width=6, fig.height=5}
p + geom_tiplab() + 
   geom_place(data=dd, map="taxa", place="value", 
              hjust=0.8, vjust=-0.4, size=4, color="red")
```

## Session Information

```{r}
sessionInfo()
```