---
date: 2017-07-24T00:11:02+01:00
title: Documentation
weight: 10
---



<link rel="stylesheet" href="https://guangchuangyu.github.io/css/font-awesome.min.css">

## <i class="fa fa-book"></i> Vignettes

+ [ggtree](https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/ggtree.html)
+ [Tree Data Import](https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/treeImport.html)
+ [Tree Visualization](https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/treeVisualization.html)
+ [Tree Annotation](https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/treeAnnotation.html)
+ [Tree Manipulation](https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/treeManipulation.html)
+ [Advance Tree Annotation](https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/advanceTreeAnnotation.html)
+ [ggtree utilities](https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/ggtreeUtilities.html)
+ [Phylomoji](https://cran.r-project.org/web/packages/emojifont/vignettes/phylomoji.html)


## <i class="fa fa-wordpress"></i> Blog posts

### <i class="fa fa-angle-double-right"></i> News and updates

+ [viewing and annotating phylogenetic tree with ggtree](https://guangchuangyu.github.io/2014/12/viewing-and-annotating-phylogenetic-tree-with-ggtree)
+ [ggtree in Bioconductor 3.1](https://guangchuangyu.github.io/2015/01/ggtree-in-bioconductor-3.1)
+ [BioC 3.1: NEWS of my BioC packages](https://guangchuangyu.github.io/2015/04/bioc-31-news-of-my-bioc-packages)
+ [BioC 3.2: NEWS of my BioC packages](https://guangchuangyu.github.io/2015/10/bioc-32-news-of-my-bioc-packages)
+ [News of ggtree](https://guangchuangyu.github.io/2015/12/news-of-ggtree)
+ [BioC 3.3: NEWS of my BioC packages](https://guangchuangyu.github.io/2016/05/bioc-33-news-of-my-bioc-packages/)
+ [BioC 3.4: NEWS of my BioC packages](https://guangchuangyu.github.io/2016/10/bioc-34-news-of-my-bioc-packages)
+ [ggtree paper published](https://guangchuangyu.github.io/2016/08/ggtree-paper-published)

### <i class="fa fa-angle-double-right"></i> Data manipulation

+ [subsetting data in ggtree](https://guangchuangyu.github.io/2015/09/subsetting-data-in-ggtree)
+ [ggtree supports phylip tree format](https://guangchuangyu.github.io/2016/01/ggtree-supports-phylip-tree-format)
+ [convert graphic object to tree object using treeio](http://guangchuangyu.github.io/2017/01/convert-graphic-object-to-tree-object-using-treeio/)

### <i class="fa fa-angle-double-right"></i> Tree visualization

+ [ggtree - updating a tree view](https://guangchuangyu.github.io/2015/02/ggtree---updating-a-tree-view/)
+ [an example of drawing beast tree using ggtree](https://guangchuangyu.github.io/2015/04/an-example-of-drawing-beast-tree-using-ggtree)
+ [Phylogenetic trees in R using ggtree](http://www.molecularecologist.com/2017/02/phylogenetic-trees-in-r-using-ggtree/) <i class="fa fa-arrow-left"></i> The Molecular Ecologist
+ [Growing a ggtree](https://phe-bioinformatics.github.io/blog/2017/06/14/ggtree_exploration)
+ [Growing a ggtree - part 2, adding tip shapes](https://phe-bioinformatics.github.io/blog/2017/07/07/ggtree_part2)

### <i class="fa fa-angle-double-right"></i> Tree annotation

+ [label edge number in ggtree](https://guangchuangyu.github.io/2016/01/label-edge-number-in-ggtree)
+ [Edge coloring with user data](http://guangchuangyu.github.io/2016/12/edge-coloring-with-user-data/)
+ [subview](https://guangchuangyu.github.io/2015/08/subview)
+ [Annotate a phylogenetic tree with insets](https://guangchuangyu.github.io/2016/01/annotate-a-phylogenetic-tree-with-insets)
+ [ggtree annotate phylogenetic tree with local images](https://guangchuangyu.github.io/2015/08/ggtree-annotate-phylogenetic-tree-with-local-images)
+ [embed images in ggplot2 via subview and annotate a phylogenetic tree with images using inset function](https://guangchuangyu.github.io/2016/03/embed-images-in-ggplot2-via-subview-and-annotate-a-phylogenetic-tree-with-images-using-inset-function)
+ [identify method for ggtree](https://guangchuangyu.github.io/2016/06/identify-method-for-ggtree)
+ [facet_plot: a general solution to associate data with phylogenetic tree](https://guangchuangyu.github.io/2016/10/facet_plot-a-general-solution-to-associate-data-with-phylogenetic-tree/)
+ [align genomic features with phylogenetic tree](https://guangchuangyu.github.io/2016/11/align-genomic-features-with-phylogenetic-tree/)
+ [ggjoy facet with ggtree](https://stackoverflow.com/questions/45384281/ggjoy-facet-with-ggtree)
+ [xlim_tree: set x axis limits for only Tree panel](https://guangchuangyu.github.io/2016/10/xlim_tree-set-x-axis-limits-for-only-tree-panel/)
+ [add layer to specific panel of facet_plot output](https://guangchuangyu.github.io/2016/12/add-layer-to-specific-panel-of-facet_plot-output/)


### <i class="fa fa-angle-double-right"></i> Tree manipulation

+ [flip and rotate branches in ggtree](https://guangchuangyu.github.io/2015/07/flip-and-rotate-branches-in-ggtree)

### <i class="fa fa-angle-double-right"></i> Application

+ [ggtree for microbiome data](https://guangchuangyu.github.io/2016/09/ggtree-for-microbiome-data/)
+ [ggtree for outbreak data](https://guangchuangyu.github.io/2016/09/ggtree-for-outbreak-data/)
+ [ggtree version of plotTree](http://guangchuangyu.github.io/2016/12/ggtree-version-of-plottree/)
+ [reproducible logo generated by ggtree](https://guangchuangyu.github.io/2016/10/reproducible-logo-generated-by-ggtree)


### <i class="fa fa-angle-double-right"></i> Funny stuff

+ [ggtree with funny fonts](https://guangchuangyu.github.io/2015/06/ggtree-with-funny-fonts)
+ [comic phylogenetic tree with ggtree and comicR](https://guangchuangyu.github.io/2015/09/comic-phylogenetic-tree-with-ggtree-and-comicr)
+ [use emoji font in R](https://guangchuangyu.github.io/2015/12/use-emoji-font-in-r)


## <i class="fa fa-slideshare"></i> Slides

+ [Generating publication quality figures using R & ggplot2](https://guangchuangyu.github.io/presentation/2014-ggplot2/)
+ [ggtree for visualization and annotation of phylogenetic trees](https://guangchuangyu.github.io/presentation/2016-ggtree-chinar/)

## <i class="fa fa-youtube-play"></i> Video

+ [interactive clade highlighting](https://www.youtube.com/watch?v=KcF8Ec38mzI)
+ [interactive rotating clades](https://www.youtube.com/watch?v=lKNn4QlPO0E)
+ [interactive clade labeling](https://www.youtube.com/watch?v=SmcceRD_jxg)

## <i class="fa fa-gift"></i> Workflow

+ [recreate a tree from a publication (__Bloom__ *et al*, __*Science*__ 2010)](https://rpubs.com/gutijosh9430/124817)
